### ISSUE TITLE
R(t) - Add UI treatment explaining when R(t) is being used or not and why

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#280] opened 2020-05-01 18:50 UTC
**Is your feature request related to a problem? Please describe.**
There are a number of data scenarios where the R(t) calculation may not be applicable, e.g. if there is not enough of a curve between observed case counts to produce a reasonable calculation. When this happens, we will not be able to:
* Include R(t) as an input to the R(0) calculation, instead falling back on user inputs
* Display an R(t) graph for the facility model on the facility details page
* Display an R(t) bubble on the facility row version of the facility model graph
* Include this facility in the R(t) procession graph in the upcoming "Rate of Spread" tab in the scenario details page
* Provide R(t) summary stats on the impact modeling page (Excalibur)

In each of these cases, we want to make sure it is obvious to users that R(t) has not been calculated/integrated, and ideally why.

We will need design work and copy for this, @cawarren.

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**
Some of the potential R(t) issues are described on #276 though there are others, so if it is important to be able to catalog the potential causes for R(t) to be incalculable/unusable, we should generate that list with help from @justkunz or @macfarlandian.

**Comment by cawarren** [comment] 2020-05-01 19:49
For #1, we should fall back on the last-good Rt if available, and if not available fall back to user inputs. That way if they simply haven't updated in a week, we're at least showing the curve that made sense last time they did update.

For #2 I'd suggest we collapse (remove) the graph except for the header, and keep that line just so we can update the (?) tooltip to explain that Rt can't be generated for this facility (and if we know why, why).

For 3 and 4, there is an '(?) / Rt not known' treatment in the mocks (see Homestead Correctional in #3, and the last entry in #4):
https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=1636%3A130

Those are intended to also have a tooltip that explains why Rt isn't there (most likely because they haven't entered enough data points).

If @justkunz can enumerate the reasons we can detect, I can write copy explaining them to the user in the respective tooltips.

@sychang for thoughts on #5 / Excalibur impact.

**Comment by macfarlandian** [comment] 2020-05-06 21:47
as of right now, the behaviors for bullet 1 and bullet 3 are in place. we should make sure to include bullet 4 in the implementation of that new chart in #202 (it's not built yet).

@cawarren We are currently just collapsing anything that goes wrong in the python function into a generic "error" response, and there's no good way to programmatically map that to a canonical "cause" in the client. If you think it's important enough, we can change that; otherwise the cause is generally just "insufficient data" (or, less likely, a network failure)

**Comment by cawarren** [comment] 2020-05-07 17:35
No I think that's great - thank you @macfarlandian

**Comment by sychang** [comment] 2020-05-12 17:30
Got some feedback that we want it to be a lot more obvious when we can't generate an R(t) and why. For #2, here is one visual option to let people know they are missing something that let's them generate an R(t) chart:

![image](https://user-images.githubusercontent.com/6633887/81725901-2789f780-944c-11ea-8c2b-8ad33a0d691a.png)

**Comment by amyrlam** [comment] 2020-05-14 19:05
Pinged Serena and Lenny on Slack. I can work on the red box empty state ^^ from https://github.com/Recidiviz/covid19-dashboard/issues/280#issuecomment-627485627

Just ping me on Slack if should change gears!

I think we mean to have it on the "rate of spread" tab on the homepage, will post up a PR shortly

**Comment by macfarlandian** [comment] 2020-05-14 19:36
@amyrlam I think this is supposed to be an error state for the Rt timeseries chart on the single facility page? not the scenario tab

**Comment by amyrlam** [comment] 2020-05-14 20:10
I'm confused. I don't have that graph on `/facility`. Is my data not set up correctly? This is what I see on /facility page below. I'll post in the channel
![screencapture-localhost-8000-facility-2020-05-14-12_16_52](https://user-images.githubusercontent.com/1372946/81980864-3e635200-95e4-11ea-9a2d-a1deb7db39a2.png)

**Comment by amyrlam** [comment] 2020-05-14 20:39
To close the loop here, I figured this out on Slack, thanks @macfarlandian!

**Comment by amyrlam** [comment] 2020-05-19 20:39
Update: I merged in https://github.com/Recidiviz/covid19-dashboard/pull/422

**Comment by jessex** [comment] 2020-05-21 17:58
I _believe_ everything that has been enumerated by product in this PR so far has already been taken care of.

@sychang there was a comment pointed towards you from Andrew above, the first comment after the issue description, asking if you wanted any specific treatment in here for Excalibur. If you do, we should make that the last sub-task of this issue. If you're happy with things as-is, we can close this out now.

**Comment by sychang** [comment] 2020-05-21 19:24
I'm fine with things as is!

**Closed** 2020-05-21 19:51 UTC
Labels: Subject: Epidemic Model, Subject: UI, Subject: UX, Type: Enhancement
