### ISSUE TITLE
[Excalibur] Show R0 summary statistics

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#227] opened 2020-04-27 04:20 UTC
Blocked by Rt calculation and UI work

PRD section: https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit#heading=h.2a9nh9h20rm5

Mock: https://www.figma.com/file/6z1QQW84a59Ul3c17PgWdV/%F0%9F%9A%80Recidiviz-CJStatus-(excalibur)?node-id=1837%3A652

**Comment by daschi** [comment] 2020-05-05 01:03
Is this a duplicate of this issue ? https://github.com/Recidiviz/covid19-dashboard/issues/239

**Comment by daschi** [comment] 2020-05-06 18:31
Closing as this was covered in #239

**Closed by daschi** 2020-05-06 18:31 UTC
Labels: Subject: Impact Tracking, Subject: UI, Subject: UX, Type: Feature
