### ISSUE TITLE
User can submit known and unknown age data at same time

### ISSUE THREAD

**Issue by glen0071** [Recidiviz/covid19-dashboard#572] opened 2020-06-15 21:57 UTC
**Describe the bug**
Users can possibly submit case/population data with conflicting known and unknown ages.

**To Reproduce**
1. In Add Cases Modal or the Facility Details page, 
2. enter cases/population data in the unknown age input boxes, 
3. then toggle to known aged inputs and enter more data. 
4. Click submit/save and it succeeds

**Expected behavior**
Submit should fail and raise Toast message "To prevent duplicate counting, known and unknown ages cannot be entered together. Please clear either the unknown age input or all age inputs."?

**Additional context**
See @macfarlandian suggestion on [PR 568](https://github.com/Recidiviz/covid19-dashboard/pull/568)

**Comment by glen0071** [comment] 2020-06-15 21:59
@jessex here's an issue that @macfarlandian suggested in my last PR. Can I get some input on the expected behavior?

Repeated from description above:
> Option 1: The repeated/conflicting amounts should be highlighted with red highlight on input box?
> Option 2: Or submit should fail and raise Toast message "To prevent duplicate counting, cannot enter known and unknown ages in same form."?

**Comment by jessex** [comment] 2020-06-16 06:21
I'll redirect that question to our PM, @sychang! Serena, thoughts on the expected behavior here?

**Comment by sychang** [comment] 2020-06-16 14:35
I think option 2 makes the most sense here because just seeing a red highlight on the input box may make it unclear what the user has to do to make the red box go away. In terms of the actual toast message, let's make the copy: 

"To prevent duplicate counting, known and unknown ages cannot be entered together. Please clear either the unknown age input or all age inputs."

**Comment by glen0071** [comment] 2020-06-16 16:08
Ok, I'll update the description with that approach.

**Comment by jessex** [comment] 2020-06-16 16:12
What happens for any inputs already saved over the last several weeks that already have known and unknown age inputs already filled in? I'm guessing the app won't reject using that data but that if that data auto-populates a form and you try to click save you will get this error message, right?

**Comment by sychang** [comment] 2020-06-16 16:14
@macfarlandian and I were discussing this in the context of shadow data and I believe that's where we landed, but Ian to confirm if that will produce any issues.

**Comment by macfarlandian** [comment] 2020-06-16 16:49
yeah that's right, we want the bad data to be visible so that people have an opportunity to fix it

**Comment by glen0071** [comment] 2020-06-23 20:08
@sychang I was playing with the known and unknown age data a lot, found some edge cases:

**First: Unexpected Togglet**
Given _known_ age data was added in the past
And I toggle the AddcCases Modal Form to view/add _unknown_ age inputs
When I try to modify _unknown_ age data in the form
Then the form flips back to the view for entering _known_ age data.

This seems like a bug in how I implemented this toggle.

**Second: Error on editing past data**
Given I entered _known_ and _unknown_ data in the past for a day
When I try to edit that data by deleting the duplicates
Then I often run into errors like "Function WriteBatch.update() called with invalid data. Unsupported field value: undefined (found in field modelInputs.ageUnknownCases)" and sometimes errors about "Failed to save. Case and death counts are cumulative, and can only increase over time". It actually seems like the save still completes, but the toast errors could be confusing.

**Third: Toast about past data**
Given I entered _known_ age data in the past
When I add _unknown_ age data today (or vise versa)
Should we raise a toast or something as they're entering the data to say "you entered x data in the past... please don't add y data now" ?

To be honest, after being away from this for a week, I kinda started implementing this Third thing before rereading the issue that's actually filed here. Oops. Would be pretty easy for me to finish it up though if it's helpful.

Not sure if I should write up issues for any of these... or if other priorities should take precedent.

**Comment by glen0071** [comment] 2020-06-23 21:37
... continuing from the comment above about **"Second: Error on editing past data"**, the nexus of errors arising from "_Function WriteBatch.update() called with invalid data..._" and "_Failed to save. Case and death counts are cumulative..._" plus adding in a new error around "_To prevent duplicate counting..._" could lead to users being unable to edit old duplicated data or add new data that is not similarly duplicated. Might we want to turn any of these errors into warnings?

**Comment by jessex** [comment] 2020-06-23 22:37
@glen0071 I think it would be helpful if you could provide a concrete example for that "Second: Error on editing past data" issue, with a screenshot of the errors/behavior you're seeing. I'm personally not totally following what's happening in that one myself, so it would be helpful to know what the data was on what day, then exactly what change you try to make, and exactly what the app does in response.

As for the "First: Unexpected toggle" issue, that does sound like something you can fix in the current scope of your work.

For the "Third: Toast about past data" issue, I think that's _not_ the behavior we want, but Serena should confirm. @sychang, we know that we don't want to add known and unknown inputs on the same day, but can a person flip back and forth between known inputs on one day and unknown on another day? It sounds like a rare use case, but I imagine we wouldn't want to prevent people from doing that, personally, e.g. if the quality or process of collecting case data from a given facility changed over time and you were no longer sure about the age brackets.

**Comment by macfarlandian** [comment] 2020-06-23 22:48
I agree that we should leave the third case alone ... it's a rare case right now but will become more likely once the shadow data feature is in place; validation behavior will have to account for that when the time comes and I would prefer we didn't make it more complicated in the meantime if we don't have to

**Comment by sychang** [comment] 2020-06-24 02:06
Agree to leave third case alone, since that is a key to making shadow data work, as Ian mentioned. Seconding the rest of Josh's comments.

**Comment by glen0071** [comment] 2020-06-24 04:13
The underlying problem might be that _deleting_ the pre-populated value leaves that input _undefined_. If a value is replaced with 0, this seems to avoid the errors I was seeing before.

That being said, to reproduce, I created a new facility and duplicated my data for today. I entered Cases: 9, Population: 500 in both the Unknown Cases and Known Cases data entry.

So now you can see the data is duplicated in the hover summary
<img width="898" alt="Screen Shot 2020-06-23 at 10 46 15 PM" src="https://user-images.githubusercontent.com/8259050/85497548-bb9ac300-b5a3-11ea-869a-65df0bedaf2e.png">

When I try to **delete** the Unknown Cases numbers in the Add Cases Modal and press save, I get an error:
<img width="735" alt="Screen Shot 2020-06-23 at 10 46 40 PM" src="https://user-images.githubusercontent.com/8259050/85498043-96f31b00-b5a4-11ea-9dfd-842bd686451c.png">

If I try to retroactively add data before today, the modal auto-populates with today's bad data. So I tried to delete the Unknown cases from there and I get an error:
<img width="706" alt="Screen Shot 2020-06-23 at 10 47 50 PM" src="https://user-images.githubusercontent.com/8259050/85498198-da4d8980-b5a4-11ea-8083-1a2073fd71a9.png">

**Comment by jessex** [comment] 2020-06-24 16:53
@macfarlandian would the right way to solve the issue Eddie walked through in the previous comment be to have some hook that automatically converts epidemic model inputs whose values are `undefined` into `null` (not sure if that would be handled better in the persistence layer) or to proactively _unset_ those fields? Any ideas here?

**Comment by macfarlandian** [comment] 2020-06-24 17:00
I have been running into this problem in the shadow data feature as well ... Firestore does seem to flip out when values are explicitly set to `undefined`. The solution I came up with in #605 was to just strip those values out in the `saveFacility` function right before they hit the database, which ought to cover this case as well once it's merged.

**Comment by jessex** [comment] 2020-06-24 17:21
Perfect. @glen0071 we're going to get Ian's PR merged today and then we'll want to rebase your branch and test your PR again to see if the same behavior occurs!

**Comment by macfarlandian** [comment] 2020-06-24 19:13
that PR is merged now FYI

**Closed** 2020-07-01 17:39 UTC
Labels: Subject: Case Tracking, Type: Bug
